### PR TITLE
Fixed test for 1.9 & refactoring.

### PR DESCRIPTION
**Pull request by cloverchio**
This pull request references #32. Resubmitted to run the build again.

### CODE REVIEW

**Comment by cloverchio** [comment]
Ah okay, I did end up reproducing this locally =[

brb

**Comment by cloverchio** [comment]
Okay, I think I have figured out as to why the 3.2, and 3.3 parts of the build fail. The version of Django: Django-1.9.2 makes use of something called  find_spec which is located in a lib called importlib.util. The problem here is that find_spec was not supported until 3.4. If the build were to run against a slightly older version of Django, Im thinking these would pass. Thoughts?

**Comment by rdegges** [comment]
I'm OK removing support for python 3.2 and 3.3 if that's ok with you. I think the most 'used' versions of Python 3 are 3.4+, so that doesn't bother me.

Want to update the .travis.yml to reflect that and try again?

**Comment by cloverchio** [comment]
Awesome! I'll update the travis.yml and try again.

**Comment by cloverchio** [comment]
Done and done.

**Comment by rdegges** [comment]
Thanks =)

**Pull request merged**
